### ISSUE TITLE
loldrivers.io is 404'ing on clicking through to individual search results

### ISSUE THREAD

**Issue by wdormann** [magicsword-io/LOLDrivers#73]
As a test, I'm trying: https://www.loldrivers.io/drivers/?query=amifldrv64.sys
which as you'll realize doesn't automatically apply the filter of `amifldrv64.sys` to the search results, which I suppose is a whole other issue altogether.

But the problem here is that if you click through on the file name (ID) or on the Category values, you'll get a 404'ing page:
https://www.loldrivers.io/drivers/drivers/6d4b0025-7910-483a-ba73-03970995edc3/
https://www.loldrivers.io/drivers/drivers/34fa6ba4-dc7c-4fd6-b947-8a0bb8ebd031/

**Comment by wdormann** [comment]
Now, just to be clear, the resulting pages are showing `404 Page not found|LOLDrivers` as a title, but there are a large number of items in the `Driver List` part of the page.  So perhaps not an actual 404?
Skimming through the first 10 or so results seems to give a wide range of results, but nothing related to my query of `amifldrv64.sys`.  So something seems to be wrong here?

**Comment by nasbench** [comment]
I'm not the frontend expert but from a quick glance, the 404 is due to a double `drivers` keyword in the URL link which is easily fixable.

As for the search you can use the table at the home page to quickly find the drivers as a temp solution, it's giving me the correct results.

![image](https://github.com/magicsword-io/LOLDrivers/assets/8741929/7298e09d-fd6f-488e-98c7-318c1fffcb15)

cc @MHaggis @josehelps
