### ISSUE TITLE
[TODO] Add Chaos Rootkit

### ISSUE THREAD

**Issue by MHaggis** [magicsword-io/LOLDrivers#98]
https://github.com/ZeroMemoryEx/Chaos-Rootkit

**Comment by MHaggis** [comment]
Added

**Comment by namazso** [comment]
.. what's the point of this? The whole point of (ab)using a vulnerable driver is that it's properly signed. If that's not a requirement, you can simply just sign your malware instead.

Or if you're interested in padding the site with fake entries, there are better (less effort) ways to go about that too.

**Comment by MHaggis** [comment]
Hi @namazso ,

Thank you for your comment. Despite being a test certificate, we have observed its misuse in real-world [situations](https://www.crowdstrike.com/blog/scattered-spider-attempts-to-avoid-detection-with-bring-your-own-vulnerable-driver-tactic/). In addition, ZeroMemoryEx (https://github.com/ZeroMemoryEx) has publicly shared a couple of vulnerable drivers, including instructions on how to exploit them. These have garnered some attention, hence, we aim to keep our project updated, regardless of whether it's a test or not.

Our analysis isn't limited to a simple hash. We strive to enrich each driver, be it malicious or vulnerable, with more than just a standard MD5/SHA1/SHA256. We offer Authentihash, TBS, and RichPEHeaderHash.

It's important to note that what doesn't work in one environment might work in another; this holds true whether it's a test certificate or not.

Your point does raise the question of whether we should introduce a new category, such as 'Experimental Drivers.' This is certainly an aspect we'll explore further as we continue our research into these types of drivers.

Thank you,
Mike

**Comment by namazso** [comment]
> Despite being a test certificate, we have observed its misuse in real-world [situations](https://www.crowdstrike.com/blog/scattered-spider-attempts-to-avoid-detection-with-bring-your-own-vulnerable-driver-tactic/).

I'm not sure what you're referring to. The post doesn't mention Chaos Rootkit, nor the test certificate it's signed with (`WDKTestCert anash,133231280654008727`). Maybe you thought there's only one single test certificate? No such thing exists, every time you install the WDK, you get a new one generated.

> Our analysis isn't limited to a simple hash. We strive to enrich each driver, be it malicious or vulnerable, with more than just a standard MD5/SHA1/SHA256. We offer Authentihash, TBS, and RichPEHeaderHash.

That's very cool, but if someone writes their driver to disk just to read it back when manual mapping it with a vulnerable driver, they're clinically braindead anyways. The earlier linked article doesn't mention it being dropped either, probably because it's a completely pointless thing to do.

FWIW only Authentihash is useful for detections. The normal hashes can be changed by just adding another signature (invalid or not doesn't matter), they're only convenient for identifying the "original" samples.

> It's important to note that what doesn't work in one environment might work in another; this holds true whether it's a test certificate or not.

I have no idea what you meant to say here. Test signatures only work if test signing is enabled. There's no other environment.

> Your point does raise the question of whether we should introduce a new category, such as 'Experimental Drivers.' This is certainly an aspect we'll explore further as we continue our research into these types of drivers.

That would definitely make a lot of sense, though I'd rather call it "Unsigned, Test signed and stolen certificates". I could easily generate a thousand of """"vulnerable"""" drivers signed with fresh test certificates each, and I'm pretty sure you can also see why filling the site with those wouldn't be particularly helpful to anyone.

Listing signed samples makes sense, because there's a limited supply of them. For the rest, let the antivirus snakeoil companies do the job of picking random strings to cry about. At that point it's only coincidental that the de-facto shellcode happens to be packaged into a .sys and signed with a WDK test cert because the default Visual Studio template does that.

I also [have a project](https://github.com/namazso/r0akmap/blob/master/r0akmap.cpp#L139-L172) that includes some shellcode mapped into kernel, yet I'd assume you don't want to dump it into a bin and upload as a "loldriver".
